project_id = "ubjemrvwfyglppfmxoep"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.analyze-cv]
verify_jwt = false

[functions.create-interview]
verify_jwt = false

[functions.trigger-call]
verify_jwt = false

[functions.twilio-answer]
verify_jwt = false

[functions.process-recording]
verify_jwt = false

[functions.get-interview]
verify_jwt = false

[functions.end-interview]
verify_jwt = false

[functions.handle-call]
verify_jwt = false

[functions.handle-vbee-call]
verify_jwt = false

[functions.initiate-vbee-call]
verify_jwt = false

[functions.vbee-callback]
verify_jwt = false

[functions.initiate-call]
verify_jwt = false

[functions.twilio-stream]
verify_jwt = false