project_id = "ubjemrvwfyglppfmxoep"

[functions.initiate-call]
verify_jwt = false

[functions.handle-call] 
verify_jwt = false

[functions.initiate-vbee-call]
verify_jwt = false

[functions.handle-vbee-call]
verify_jwt = false

[functions.process-recording]
verify_jwt = false

[functions.analyze-cv]
verify_jwt = false