// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubjemrvwfyglppfmxoep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViamVtcnZ3ZnlnbHBwZm14b2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDA3MTIsImV4cCI6MjA2Mjg3NjcxMn0.jsA5r5XkMFUB5W4fL81tCR22dFIq_rKLh3ZItjjBVnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});